# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'after_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MsgWindow(object):
    def OpenLogin(self,MsgWindow):
        from login_page import Ui_loginWindow
        self.window=QtWidgets.QMainWindow()
        self.ui = Ui_loginWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MsgWindow.hide()
        
    def setupUi(self, MsgWindow):
        MsgWindow.setObjectName("MsgWindow")
        MsgWindow.resize(500, 489)
        self.centralwidget = QtWidgets.QWidget(MsgWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 40, 283, 90))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RegistrationMsgLbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.RegistrationMsgLbl.setFont(font)
        self.RegistrationMsgLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.RegistrationMsgLbl.setObjectName("RegistrationMsgLbl")
        self.verticalLayout.addWidget(self.RegistrationMsgLbl)
        spacerItem = QtWidgets.QSpacerItem(232, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.GotoLoginButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.GotoLoginButton.setFont(font)
        self.GotoLoginButton.setObjectName("GotoLoginButton")
        self.GotoLoginButton.clicked.connect(lambda: self.OpenLogin(MsgWindow))
        self.verticalLayout.addWidget(self.GotoLoginButton)
        MsgWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MsgWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MsgWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MsgWindow)
        self.statusbar.setObjectName("statusbar")
        MsgWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MsgWindow)
        QtCore.QMetaObject.connectSlotsByName(MsgWindow)

    def retranslateUi(self, MsgWindow):
        _translate = QtCore.QCoreApplication.translate
        MsgWindow.setWindowTitle(_translate("MsgWindow", "Msg_Page"))
        self.RegistrationMsgLbl.setText(_translate("MsgWindow", "Registration message"))
        self.GotoLoginButton.setText(_translate("MsgWindow", "Go to Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MsgWindow = QtWidgets.QMainWindow()
    ui = Ui_MsgWindow()
    ui.setupUi(MsgWindow)
    MsgWindow.show()
    sys.exit(app.exec_())
