# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerateReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportWindow(object):
    def setupUi(self, ReportWindow):
        ReportWindow.setObjectName("ReportWindow")
        ReportWindow.resize(919, 621)
        self.centralwidget = QtWidgets.QWidget(ReportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.StrtMsgLbl = QtWidgets.QLabel(self.centralwidget)
        self.StrtMsgLbl.setGeometry(QtCore.QRect(30, 60, 351, 31))
        self.StrtMsgLbl.setObjectName("StrtMsgLbl")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 281, 16))
        self.label_2.setObjectName("label_2")
        self.recomjob = QtWidgets.QLabel(self.centralwidget)
        self.recomjob.setGeometry(QtCore.QRect(610, 180, 301, 241))
        self.recomjob.setObjectName("recomjob")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 200, 55, 16))
        self.label_5.setObjectName("label_5")
        self.RecomCB = QtWidgets.QComboBox(self.centralwidget)
        self.RecomCB.setGeometry(QtCore.QRect(350, 110, 331, 22))
        self.RecomCB.setObjectName("RecomCB")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 211, 16))
        self.label_3.setObjectName("label_3")
        self.WeakLbl = QtWidgets.QLabel(self.centralwidget)
        self.WeakLbl.setGeometry(QtCore.QRect(240, 200, 181, 181))
        self.WeakLbl.setObjectName("WeakLbl")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(110, 450, 93, 28))
        self.BackButton.setObjectName("BackButton")
        ReportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 26))
        self.menubar.setObjectName("menubar")
        ReportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReportWindow)
        self.statusbar.setObjectName("statusbar")
        ReportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReportWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportWindow)

    def retranslateUi(self, ReportWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportWindow.setWindowTitle(_translate("ReportWindow", "Career Report"))
        self.label.setText(_translate("ReportWindow", "Career Report"))
        self.StrtMsgLbl.setText(_translate("ReportWindow", "Dear, "))
        self.label_2.setText(_translate("ReportWindow", "We Recommend that you the following Courses:"))
        self.recomjob.setText(_translate("ReportWindow", "Job List"))
        self.label_5.setText(_translate("ReportWindow", "Jobs:"))
        self.label_3.setText(_translate("ReportWindow", "Your Weaknesses lie in these areas:"))
        self.WeakLbl.setText(_translate("ReportWindow", "TextLabel"))
        self.BackButton.setText(_translate("ReportWindow", "Back To Menu"))

    def Back(self, ReportWindow):
        from menu_page import Ui_MenuWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MenuWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MenuWindow.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportWindow = QtWidgets.QMainWindow()
    ui = Ui_ReportWindow()
    ui.setupUi(ReportWindow)
    ReportWindow.show()
    sys.exit(app.exec_())
