# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
con = sqlite3.connect("G:\reps\minor-project\Database\Career_Recommedation_System.db")

class Registration(object):
    def setupUi(self, MainWindow):
        self.cur = con.cursor()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 496)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.splitter)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.FirstNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FirstNameLineEdit.setObjectName("FirstNameLineEdit")
        self.verticalLayout.addWidget(self.FirstNameLineEdit)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.LastNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LastNameLineEdit.setObjectName("LastNameLineEdit")
        self.verticalLayout.addWidget(self.LastNameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.UserIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserIdLineEdit.setObjectName("UserIdLineEdit")
        self.verticalLayout.addWidget(self.UserIdLineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setObjectName("registerButton")
        self.registerButton.clicked.connect(self.Register)
        self.verticalLayout.addWidget(self.registerButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration Form"))
        self.label_3.setText(_translate("MainWindow", "Registration"))
        self.label_5.setText(_translate("MainWindow", "First Name"))
        self.label_6.setText(_translate("MainWindow", "Last Name"))
        self.label_2.setText(_translate("MainWindow", "User Id"))
        self.label.setText(_translate("MainWindow", "Password"))
        self.registerButton.setText(_translate("MainWindow", "Register"))

    def Register(self):
        firstname=self.FirstNameLineEdit.text()
        lastname=self.LastNameLineEdit.text()
        userid=self.UserIdLineEdit.text()
        password=self.PasswordLineEdit.text()
        statement= f"INSERT INTO user_info VALUES('{userid}', '{firstname}', '{lastname}', '{password}')"
        self.cur.execute(statement)
        con.commit()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Registration()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

