# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'take test all other questions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakeTestWindow(object):
    def setupUi(self, TakeTestWindow):
        TakeTestWindow.setObjectName("TakeTestWindow")
        TakeTestWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TakeTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Option2Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Option2Button.setGeometry(QtCore.QRect(40, 230, 95, 20))
        self.Option2Button.setObjectName("Option2Button")
        self.AnswerbuttonGroup = QtWidgets.QButtonGroup(TakeTestWindow)
        self.AnswerbuttonGroup.setObjectName("AnswerbuttonGroup")
        self.AnswerbuttonGroup.addButton(self.Option2Button)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 781, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Option4Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Option4Button.setGeometry(QtCore.QRect(40, 330, 95, 20))
        self.Option4Button.setObjectName("Option4Button")
        self.AnswerbuttonGroup.addButton(self.Option4Button)
        self.Option1Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Option1Button.setGeometry(QtCore.QRect(40, 180, 95, 20))
        self.Option1Button.setObjectName("Option1Button")
        self.AnswerbuttonGroup.addButton(self.Option1Button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(620, 460, 93, 28))
        self.NextButton.setObjectName("NextButton")
        self.Option3Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Option3Button.setGeometry(QtCore.QRect(40, 280, 95, 20))
        self.Option3Button.setObjectName("Option3Button")
        self.AnswerbuttonGroup.addButton(self.Option3Button)
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(80, 460, 93, 28))
        self.BackButton.setObjectName("BackButton")
        TakeTestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TakeTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        TakeTestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TakeTestWindow)
        self.statusbar.setObjectName("statusbar")
        TakeTestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TakeTestWindow)
        QtCore.QMetaObject.connectSlotsByName(TakeTestWindow)

    def retranslateUi(self, TakeTestWindow):
        _translate = QtCore.QCoreApplication.translate
        TakeTestWindow.setWindowTitle(_translate("TakeTestWindow", "Test_Page"))
        self.Option2Button.setText(_translate("TakeTestWindow", "Option2"))
        self.label_2.setText(_translate("TakeTestWindow", "Question"))
        self.Option4Button.setText(_translate("TakeTestWindow", "Option4"))
        self.Option1Button.setText(_translate("TakeTestWindow", "Option1"))
        self.label.setText(_translate("TakeTestWindow", "Question NO. 0"))
        self.NextButton.setText(_translate("TakeTestWindow", "Next"))
        self.Option3Button.setText(_translate("TakeTestWindow", "Option3"))
        self.BackButton.setText(_translate("TakeTestWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TakeTestWindow = QtWidgets.QMainWindow()
    ui = Ui_TakeTestWindow()
    ui.setupUi(TakeTestWindow)
    TakeTestWindow.show()
    sys.exit(app.exec_())
